<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        User::factory()->create([
            'name' => 'Test User',
            'email' => 'test@example.com',
            'password' => bcrypt('password'), // Use a hashed password
        ]);

        // You can use either the CivilizationSeeder (with real data from JSON)
        // or the TestDataSeeder (with fake data generated by factories)

        // Comment out one of these based on your needs
        $this->call([
            CivilizationSeeder::class,
            // TestDataSeeder::class,
        ]);

        // Or to use the TestDataSeeder only:
        // $this->call(TestDataSeeder::class);
    }
}
